require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RelatedDigitalNotificationService' do
  pod 'react-native-related-digital', :path => '../node_modules/react-native-related-digital'
  
  use_native_modules!
end

# Post Install processing for RelatedDigitalNotificationService causing errors
def notification_service_post_install(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end

target 'jimmyKeyProject' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'jimmyKeyProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  post_install do |installer|
    # flipper_post_install(installer)
    notification_service_post_install(installer)
  end
end

target 'jimmyKeyProject-tvOS' do
  # Pods for jimmyKeyProject-tvOS

  target 'jimmyKeyProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
